### ISSUE TITLE
getBuildingIO function does not take into account the output of markets

### ISSUE THREAD

**Issue by jimmyh77** [fishpondstudio/CivIdle#108]
https://github.com/fishpondstudio/CivIdle/blob/e01591e9e046f5d4eb0e0d5b7980985893a10352/shared/logic/IntraTickCache.ts#L33

This means that Censor's Office is inaccurate when markets are used.

**Comment by insraq** [comment]
> https://github.com/fishpondstudio/CivIdle/blob/e01591e9e046f5d4eb0e0d5b7980985893a10352/shared/logic/IntraTickCache.ts#L33
> 
> This means that Censor's Office is inaccurate when markets are used.

I manually incorporated the change in https://github.com/fishpondstudio/CivIdle/commit/544a2da4bb45bb90b3e13918768d4ee3632155db

Let me know if I screw up anything. Thanks!

**Comment by jimmyh77** [comment]
@insraq Added a comment to the commit https://github.com/fishpondstudio/CivIdle/commit/544a2da4bb45bb90b3e13918768d4ee3632155db
