### ISSUE TITLE
Percentage of Transportation Workers in Statistics Building is broken

### ISSUE THREAD

**Issue by insraq** [fishpondstudio/CivIdle#123]
Ref https://discord.com/channels/631551126377857044/1102225155830317136/1212855978861793350

**Comment by jimmyh77** [comment]
@insraq This code got change last week.

```
                     mReduceOf(
                        gameState.transportation,
                        (prev, k, v) => prev + v.reduce((prev, curr) => prev + curr.currentFuelAmount, 0),
                        0,
                     ) / Tick.current.workersUsed.get("Power")!,
```

From this!!

```
                     mReduceOf(
                        gameState.transportation,
                        (prev, k, v) => prev + v.reduce((prev, curr) => prev + curr.currentFuelAmount, 0),
                        0,
                     ) / Tick.current.workersUsed.Worker!,
```

**Comment by insraq** [comment]
Oh, that's wrong. It should be `Tick.current.workersUsed.get("Worker")`

**Comment by insraq** [comment]
Do you want to make a PR? I am on the 0.3 branch

**Comment by jimmyh77** [comment]
PR for main or 0.3?

**Comment by jimmyh77** [comment]
Not sure how they have that big a number, mine is NaN

**Comment by insraq** [comment]
This should be fixed in `main`.
If you have power, then it will show a big number (which is wrong, it's using power instead of worker)

**Comment by jimmyh77** [comment]
PR here https://github.com/fishpondstudio/CivIdle/pull/124
