### ISSUE TITLE
Storage panel width

### ISSUE THREAD

**Issue by skydochwm** [fishpondstudio/CivIdle#158]
Resourse transport groupbox in "Storage" right panel crawls off the edge of the screen when selecting the Russian language. Impossible click to checkbox "Export below max amount".
![image](https://github.com/fishpondstudio/CivIdle/assets/34720942/22853a93-632d-460d-b74f-0b71382b97a3)

**Comment by WingedLeo** [comment]
![изображение](https://github.com/fishpondstudio/CivIdle/assets/93556692/2b03b13c-e60a-426b-ac82-f785040f3801)
Change the panel width
