### ISSUE TITLE
Caravansary Resource Drop Down Keep Jumping Around

### ISSUE THREAD

**Issue by EurypteriD192** [fishpondstudio/CivIdle#162]
So items in the caravansy keeps changing due to items moving/removeing or added to the list 
every second right now it shifts between bricks and sand, it just caused me to put 4000 tools up for sand instead bricks.

**Comment by insraq** [comment]
This should be fixed in 0.4.0? Does it still happen to you?

**Comment by EurypteriD192** [comment]
Yes in 0.40 I can reproduce it. Feel free to dm me on discord and I can
give you screenshot /recording.

**Comment by insraq** [comment]
Can you post a screenshot? Which list are you referring to? The dropdown menu?

**Comment by EurypteriD192** [comment]
![image](https://github.com/fishpondstudio/CivIdle/assets/8395795/6fc01ca8-3cd2-4bf0-8294-e665ba1a54c3)
![image](https://github.com/fishpondstudio/CivIdle/assets/8395795/3acfbf14-21fe-4027-989f-043081aab331)
This should be both screen shots showing the menu moving

**Comment by insraq** [comment]
Thanks, this is an known issue, will keep this open for tracking

**Comment by EurypteriD192** [comment]
Looking at it. trying to figure out what ones being added it looks to be rotating between 3-4 different.. 
chariot Alcohol, Bond marble
