### ISSUE TITLE
[Feature Request] Add "Go Back to City" shortcut key in the option menu

### ISSUE THREAD

**Issue by HanzCEO** [fishpondstudio/CivIdle#17]
![image](https://github.com/fishpondstudio/CivIdle/assets/40712686/48fdfd07-872b-441b-9c58-930d7f4ac395)
Forwarding this here

Instead of individually set a key to exit a scene to go back to the city scene, can we have a master key to go back to city instead? This way, the option can be modular as how a good programming practices are, being modular.

**Comment by insraq** [comment]
Fixed by 512790d50162fb3c5dae79690bb0a103893d7b3b
