### ISSUE TITLE
Support linux

### ISSUE THREAD

**Issue by Q300Z** [fishpondstudio/CivIdle#181]
When i'm on the loading screen and press "S" to open the save folder : 
![image](https://github.com/fishpondstudio/CivIdle/assets/34000576/0f6518d1-ec1e-4dbd-b968-0d7f4ba5f781)
The error message :
No Windows program is configured to open this file type

In full screen mode, clicking on a cell selects the cell next to it

System: Arch Manjaro with Plasma 6

**Comment by xyzzycgn** [comment]
After update to 0.7.1 with experimental native Linux build game refuses to start

**Comment by insraq** [comment]
0.7.1 should fix this
