### ISSUE TITLE
Unable to connect to game server

### ISSUE THREAD

**Issue by vn-vna** [fishpondstudio/CivIdle#235]
When I start the game, it gets stuck at "Connecting to Steam..." for a while
![image](https://github.com/fishpondstudio/CivIdle/assets/63695659/c0dda115-83b1-4598-8cb1-6f05d9bf0c5d)

Then, when game is finally launched, it says "Error: Connection timeout". Then nothing happened and I can't reconnect. I didn't receive any offline production value from my town.
![image](https://github.com/fishpondstudio/CivIdle/assets/63695659/d26429b0-64b4-4d40-9b96-29abd548aa0c)

This situation has happened for 2 weeks, I tried using mirror server option in gameplay menu but it is not work at all.

**Comment by insraq** [comment]
If you build Petra, you should get warps based on your offline time once you finally reconnect. Does this not happen? If not, can you provide your game log?
