### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by jgestiot** [fishpondstudio/CivIdle#287]
The resource sliders should be red while incomplete and then turn green when completed. I know it is a minor point but having the colors the wrong way around breaches standard interface rules.

**Comment by insraq** [comment]
I am not sure I understand. Can you elaborate?

**Comment by jgestiot** [comment]
Currently the slider color green indicates an insufficient resource and the
color red indicates a resource fulfilled. It should be the other
way around. In user interfaces you indicate a negative with red and a
positive with green.

Cheers,

JG

**Comment by insraq** [comment]
Which "Resource Slider" are you referring to? Can you take a screenshot and add more details?
