### ISSUE TITLE
Ambiguous effect of Zagros Mountains

### ISSUE THREAD

**Issue by jk15162428** [fishpondstudio/CivIdle#307]
The effect of Zagros Mountains said, "All adjacent buildings that have less than 5 Production Multiplier get +2 Production Multiplier."
Here is a screenshot from my side @ July 26th.
<img width="475" alt="screenshot" src="https://github.com/user-attachments/assets/0f12e355-f553-4377-b8a0-2713c3a6ad7c">

The selected Bank (highlighted) is adjacent, and it has x7 production multiplier, so anything else (except the mountain) provides 5 production multiplier. However, the bank still takes the buff from Zagros Mountains.

After the multiplier gets higher, the effect is gone, which is expected.

<img width="523" alt="screenshot2" src="https://github.com/user-attachments/assets/47102e80-ce9b-404c-9f8f-6613e46eef0b">

I guess the problem is because the base multiplier does not count / or the description is wrong (which should be less than or equal than, or less than 6, not 5)

**Comment by insraq** [comment]
Thanks, this is indeed confusing. To clarify:
1) Base multiplier should count (currently it doesn't, which is a bug)
2) It is `< 5`, not `<= 5`
3) When comparing with 5, it excludes the multiplier from Zagros Mountain itself

**Comment by jk15162428** [comment]
So it is a bug, thanks for clarification. Then there is no error with the description.
