### ISSUE TITLE
Oxford university doesn't give much science.

### ISSUE THREAD

**Issue by WingedLeo** [fishpondstudio/CivIdle#35]
It's probably worth adding some kind of boost to it.
Or give more science per building level
![screenshot 1702995292](https://github.com/fishpondstudio/CivIdle/assets/93556692/2588fdbe-3440-420f-8f5f-1edceac78a94)

(With 1400 buildings, I only get 20k of science.)

**Comment by insraq** [comment]
Yes. I will do a balancing in the next balancing patch (post EA).
Do you have a number in mind? I am thinking about +10 per upgrade, maybe it's too OP?

**Comment by WingedLeo** [comment]
At the time, my workers were giving me 400k science/s... If I have to build the same amount to get 200k, I think that would be an okay number considering where this building is in the tech branch

**Comment by WingedLeo** [comment]
It is even possible, for balancing purposes, to increase the cost of the wonder itself

**Comment by insraq** [comment]
Fixed in 0.3.0
