### ISSUE TITLE
Clean up residual construction materials after construction complete

### ISSUE THREAD

**Issue by insraq** [fishpondstudio/CivIdle#45]
https://discord.com/channels/631551126377857044/1205701004838969364

**Comment by jimmyh77** [comment]
Is this literally just doing a `building.resources = {}` when building is complete in `tickTile`?

**Comment by insraq** [comment]
It's not that simple :-)
The problem is, when the building finishes construction, there might be resources being transported to the building, which will arrive *after* the building finishes.

**Comment by jimmyh77** [comment]
So a better place to look is why more than needed resources are being transported?

I feel like this should not set `completed = false;`
```
         // Will be full
         if (amountArrived + getAmountInTransit(xy, res, gs) >= amount) {
            completed = false;
            // continue;
            return false;
         }
```
I would have thought if it will be full then it will be completed.

https://github.com/fishpondstudio/CivIdle/blob/443b62aa8b7fe0a0b7ee31b95a1e0ffd5022e89e/shared/logic/Update.ts#L209

**Comment by jimmyh77** [comment]
Actually ignore that, otherwise it will complete the building below, when resources are still in transit.

**Comment by insraq** [comment]
Instead of a boolean, it should be an enum and a small state machine:

`State = { Transporting, Completing, Completed }`

**Comment by jimmyh77** [comment]
Will this code change with `New Construction/Upgrade Flow` in 0.3.0?  If not I can have a play around with this and try and get it so only the needed amount are transported.

**Comment by insraq** [comment]
No. This should be a simple fix - I can fix it in the next build - if you want to double check whether my fix is good :-)

**Comment by jimmyh77** [comment]
I can, but actually thinking about it.

The call to `transportResource` passes in `builderCapacityPerResource`  should this, I think it's the first one, should this value not be less if the amount left to transport is less then `buildingCapacityPerResource`

**Comment by insraq** [comment]
> I can, but actually thinking about it.
> 
> The call to `transportResource` passes in `builderCapacityPerResource` , I think it's the first one, should this value not be less if the amount left to transport is less then `buildingCapacityPerResource`

Does this fix look good to you? https://github.com/fishpondstudio/CivIdle/commit/3307990a16ba8cdf8b8c7eef1fc8cec377002694

**Comment by jimmyh77** [comment]
That looks good to me 👍
