### ISSUE TITLE
Sort Caravansary "I Want" and "I Offer" dropdown

### ISSUE THREAD

**Issue by insraq** [fishpondstudio/CivIdle#47]
https://discord.com/channels/631551126377857044/1206694969578889256

**Comment by jimmyh77** [comment]
There is a PR for it here. https://github.com/fishpondstudio/CivIdle/pull/40

**Comment by insraq** [comment]
Great, I am converting all the Discord posts to Github. Discord becomes unmanageable really quickly :-)

**Comment by jimmyh77** [comment]
> Great, I am converting all the Discord posts to Github. Discord becomes unmanageable really quickly :-)

Agreed, having all issues/feature requests all in one places allows people like myself to pick something and create a PR for it.   It can just be time consuming to maintain this.

**Comment by insraq** [comment]
Yes, this will also serve as kind of a "roadmap" as well.
I don't particularly enjoy project management but I guess I just need to put my mind to it.

**Comment by jimmyh77** [comment]
Same here, I'm sure some one from the community would love to do it 😂
