### ISSUE TITLE
Chinese font does not show up in Tech Tree

### ISSUE THREAD

**Issue by insraq** [fishpondstudio/CivIdle#55]
![image](https://github.com/fishpondstudio/CivIdle/assets/608221/e8b3b268-e153-4bf7-8e7e-3eb71b0870c5)

**Comment by QZshallowsing** [comment]
I've noticed this since the first Chinese translation update, but neither English nor the translated Russian have similar issues. Since the right side can be translated normally, is there any corresponding limitation in the text setting of the technology tree panel?

**Comment by insraq** [comment]
Fixed in 0.1.138
